# Generated by Django 4.2.7 on 2023-11-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_Tab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Support_Engineer', models.CharField(max_length=100, null=True)),
                ('User_name', models.CharField(max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=15, null=True)),
                ('LCO', models.CharField(max_length=225, null=True)),
                ('Issue', models.CharField(max_length=100, null=True)),
                ('Remark', models.CharField(max_length=225, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('ESCALATION', models.CharField(max_length=100, null=True)),
                ('ESCALATION_REMARK', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESCALATION_Tab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ESCALATION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issue_Tab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Issue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Tab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Support_Engineer_tab',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Support_Engineer', models.CharField(max_length=100)),
            ],
        ),
    ]
